/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'scott' at '2/29/16 11:23 PM' with Gradle 2.3
 *
 * @author scott, @date 2/29/16 11:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
